spring.application.name=tutor-ollama-redes

# =========================
# Gemini
# =========================

spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.ai.google.genai.chat.temperature=0.7


# =========================
# Ollama
# =========================

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.chat.temperature=0.7
